-- CreateEnum
CREATE TYPE "CurrencyCode" AS ENUM ('VND');

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('CUSTOMER', 'ADMIN', 'CONTENT_EDITOR', 'OPS');

-- CreateEnum
CREATE TYPE "AdminPermission" AS ENUM ('CATALOG_MANAGE', 'CONTENT_REVIEW', 'ORDER_MANAGE', 'ANALYTICS_VIEW');

-- CreateEnum
CREATE TYPE "AvailabilityStatus" AS ENUM ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK');

-- CreateEnum
CREATE TYPE "PublishStatus" AS ENUM ('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('PLACED', 'AWAITING_TRANSFER', 'CONFIRMED', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'AWAITING_VERIFICATION', 'PAID', 'FAILED');

-- CreateEnum
CREATE TYPE "PaymentMethodCode" AS ENUM ('COD', 'BANK_TRANSFER');

-- CreateEnum
CREATE TYPE "AnalyticsEventName" AS ENUM ('PAGE_VIEW', 'SESSION_START', 'VIEW_HOMEPAGE', 'VIEW_LANDING_PAGE', 'SEARCH', 'VIEW_SEARCH_RESULTS', 'SEARCH_NO_RESULT', 'SELECT_SEARCH_RESULT', 'VIEW_CATEGORY', 'VIEW_COLLECTION', 'APPLY_FILTER', 'REMOVE_FILTER', 'APPLY_SORT', 'CLICK_PRODUCT_CARD', 'VIEW_ITEM', 'CLICK_RELATED_PRODUCT', 'ADD_TO_CART', 'REMOVE_FROM_CART', 'UPDATE_CART_QUANTITY', 'VIEW_CART', 'BEGIN_CHECKOUT', 'ADD_SHIPPING_INFO', 'SELECT_PAYMENT_METHOD', 'CHECKOUT_ERROR', 'PURCHASE', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED');

-- CreateTable
CREATE TABLE "AppHealthcheck" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AppHealthcheck_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AppHealthcheck_label_key" ON "AppHealthcheck"("label");
